# Generated by Django 3.1.12 on 2024-12-01 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_ticket_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
