# Generated by Django 5.1.2 on 2024-11-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='about_item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_info',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
